# Generated by Django 5.2.9 on 2026-03-19 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='actors',
            field=models.ManyToManyField(related_name='acted_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('star', 'Star'), ('share', 'Share'), ('repost', 'Repost'), ('message', 'Message'), ('video', 'Video'), ('starred', 'Starred')], max_length=20),
        ),
    ]
