# Generated by Django 5.2.9 on 2026-05-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_options_notification_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment_like', 'Comment Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('star', 'Star'), ('connected', 'Connected'), ('connection_request', 'Connection Request'), ('connection_accept', 'Connection Accept'), ('connection_declined', 'Connection Declined'), ('share', 'Share'), ('repost', 'Repost'), ('message', 'Message'), ('video', 'Video'), ('community', 'Community'), ('invite', 'Invite'), ('invite_accept', 'Invite Accept'), ('approval', 'Approval')], max_length=20),
        ),
    ]
