# Generated by Django 5.2.9 on 2026-07-02 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_alter_triberequest_options_and_more'),
        ('notifications', '0008_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tribe_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='communities.triberequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment_like', 'Comment Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('star', 'Star'), ('connected', 'Connected'), ('connection_request', 'Connection Request'), ('connection_accept', 'Connection Accept'), ('connection_declined', 'Connection Declined'), ('share', 'Share'), ('repost', 'Repost'), ('message', 'Message'), ('video', 'Video'), ('community', 'Community'), ('invite', 'Invite'), ('invite_accept', 'Invite Accept'), ('join_rejected', 'Join Rejected'), ('join_approved', 'Join Approved'), ('join_request', 'Join Request'), ('community_ban', 'Community Ban'), ('community_unban', 'Community Unban'), ('moderator_added', 'Moderator Added'), ('admin_added', 'Admin Added'), ('role_removed', 'Role Removed'), ('post_approved', 'Post Approved'), ('post_rejected', 'Post Rejected'), ('approval', 'Approval'), ('tribe_request_rejected', 'Tribe Request Rejected'), ('tribe_request_approved', 'Tribe Request Approved')], max_length=50),
        ),
    ]
