# Generated by Django 5.2.9 on 2026-07-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_triberequest_tribe'),
        ('notifications', '0009_notification_tribe_request_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='communities.community'),
        ),
    ]
