# Generated by Django 5.2.9 on 2026-08-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment_like', 'Comment Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('star', 'Star'), ('connected', 'Connected'), ('connection_request', 'Connection Request'), ('connection_accept', 'Connection Accept'), ('connection_declined', 'Connection Declined'), ('share', 'Share'), ('repost', 'Repost'), ('message', 'Message'), ('video', 'Video'), ('community', 'Community'), ('invite', 'Invite'), ('invite_accept', 'Invite Accept'), ('join_rejected', 'Join Rejected'), ('join_approved', 'Join Approved'), ('join_request', 'Join Request'), ('community_ban', 'Community Ban'), ('community_unban', 'Community Unban'), ('community_removed', 'Community Removed'), ('moderator_added', 'Moderator Added'), ('admin_added', 'Admin Added'), ('role_removed', 'Role Removed'), ('post_approved', 'Post Approved'), ('post_rejected', 'Post Rejected'), ('approval', 'Approval'), ('post_deleted_by_admin', 'Post Deleted By Admin'), ('tribe_request_rejected', 'Tribe Request Rejected'), ('tribe_request_approved', 'Tribe Request Approved')], max_length=50),
        ),
    ]
