# Generated by Django 5.2.9 on 2026-08-19 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('community', 'Community'), ('recommendation', 'Recommendation'), ('marketing', 'Marketing'), ('like', 'Like'), ('comment_like', 'Comment Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('star', 'Star'), ('bookmark', 'Bookmark'), ('connected', 'Connected'), ('connection_request', 'Connection Request'), ('connection_accept', 'Connection Accept'), ('connection_declined', 'Connection Declined'), ('share', 'Share'), ('repost', 'Repost'), ('message', 'Message'), ('video', 'Video'), ('community', 'Community'), ('invite', 'Invite'), ('invite_accept', 'Invite Accept'), ('join_rejected', 'Join Rejected'), ('join_approved', 'Join Approved'), ('join_request', 'Join Request'), ('community_ban', 'Community Ban'), ('community_unban', 'Community Unban'), ('community_removed', 'Community Removed'), ('moderator_added', 'Moderator Added'), ('admin_added', 'Admin Added'), ('role_removed', 'Role Removed'), ('post_approved', 'Post Approved'), ('post_rejected', 'Post Rejected'), ('approval', 'Approval'), ('post_deleted_by_admin', 'Post Deleted By Admin'), ('tribe_request_rejected', 'Tribe Request Rejected'), ('tribe_request_approved', 'Tribe Request Approved')], max_length=50),
        ),
        migrations.CreateModel(
            name='DevicePushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('invalid_token', 'Invalid Token'), ('skipped', 'Skipped')], default='queued', max_length=30)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.devicepushtoken')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('social_notifications', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('community_notifications', models.BooleanField(default=True)),
                ('recommendation_notifications', models.BooleanField(default=True)),
                ('marketing_notifications', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='devicepushtoken',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f95ba1_idx'),
        ),
    ]
