# Generated by Django 5.2.9 on 2026-08-19 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_alter_notification_type_devicepushtoken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationdelivery',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('community', 'Community'), ('recommendation', 'Recommendation'), ('marketing', 'Marketing'), ('announcement', 'Announcement'), ('like', 'Like'), ('comment_like', 'Comment Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('star', 'Star'), ('bookmark', 'Bookmark'), ('connected', 'Connected'), ('connection_request', 'Connection Request'), ('connection_accept', 'Connection Accept'), ('connection_declined', 'Connection Declined'), ('share', 'Share'), ('repost', 'Repost'), ('message', 'Message'), ('video', 'Video'), ('community', 'Community'), ('invite', 'Invite'), ('invite_accept', 'Invite Accept'), ('join_rejected', 'Join Rejected'), ('join_approved', 'Join Approved'), ('join_request', 'Join Request'), ('community_ban', 'Community Ban'), ('community_unban', 'Community Unban'), ('community_removed', 'Community Removed'), ('moderator_added', 'Moderator Added'), ('admin_added', 'Admin Added'), ('role_removed', 'Role Removed'), ('post_approved', 'Post Approved'), ('post_rejected', 'Post Rejected'), ('approval', 'Approval'), ('post_deleted_by_admin', 'Post Deleted By Admin'), ('tribe_request_rejected', 'Tribe Request Rejected'), ('tribe_request_approved', 'Tribe Request Approved')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['user', '-score'], name='notificatio_user_id_82f347_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['topic', '-score'], name='notificatio_topic_95349d_idx'),
        ),
        migrations.AddConstraint(
            model_name='userinterest',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_user_interest_topic'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', '-score'], name='notificatio_user_id_4def87_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'recommended_user'), name='unique_user_recommended_user'),
        ),
    ]
