# Generated by Django 5.2.9 on 2026-08-25 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0028_message_client_created_at_alter_message_media_source'),
        ('communities', '0018_community_cover_image_asset_and_more'),
        ('notifications', '0015_pushnotificationdelivery_scheduled_for_and_more'),
        ('post', '0032_remove_bookmark_unique_user_post_bookmark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrecommendation',
            name='unique_user_recommended_user',
        ),
        migrations.RemoveIndex(
            model_name='userrecommendation',
            name='notificatio_user_id_4def87_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='recommendation_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pushnotificationdelivery',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pushnotificationdelivery',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='chats.message'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='communities.community'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='post.post'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('people', 'People'), ('post', 'Post'), ('community', 'Community')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pushnotificationdelivery',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='notifications.notification'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='recommended_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'recommendation_type', '-score'], name='notificatio_user_id_4f3307_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushnotificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('message__isnull', True), ('notification__isnull', False)), models.Q(('message__isnull', False), ('notification__isnull', True)), _connector='OR'), name='delivery_has_one_source'),
        ),
        migrations.AddConstraint(
            model_name='pushnotificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'device'), name='unique_notification_device_delivery'),
        ),
        migrations.AddConstraint(
            model_name='pushnotificationdelivery',
            constraint=models.UniqueConstraint(fields=('message', 'device'), name='unique_message_device_delivery'),
        ),
    ]
