# Generated by Django 5.2.9 on 2026-09-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_userrecommendation_unique_user_recommended_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicepushtoken',
            name='browser',
            field=models.TextField(blank=True),
        ),
    ]
