# Generated by Django 5.2.9 on 2026-09-07 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_alter_devicepushtoken_browser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicepushtoken',
            name='token',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='devicepushtoken',
            index=models.Index(fields=['token', 'is_active'], name='notificatio_token_cf4501_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicepushtoken',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='unique_user_push_token'),
        ),
    ]
