# Generated by Django 5.2.9 on 2026-04-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_is_approved_post_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.URLField(),
        ),
    ]
