# Generated by Django 5.2.9 on 2026-04-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postmedia_thumbnail_alter_postmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
