# Generated by Django 5.2.9 on 2026-05-01 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='post.post'),
        ),
    ]
