# Generated by Django 5.2.9 on 2026-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postview',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postview',
            name='watch_time',
            field=models.FloatField(default=0),
        ),
    ]
