# Generated by Django 5.2.9 on 2026-05-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_postview_completed_postview_skipped_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='postview',
            name='last_viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postview',
            name='replay_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postview',
            name='skipped_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postview',
            name='skipped',
            field=models.IntegerField(default=0),
        ),
    ]
