# Generated by Django 5.2.9 on 2026-05-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_postview_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postview',
            name='skipped_views',
        ),
        migrations.AddField(
            model_name='post',
            name='skipped_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postview',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
