# Generated by Django 5.2.9 on 2026-05-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_remove_postview_skipped_views_post_skipped_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replay_count',
            field=models.IntegerField(default=0),
        ),
    ]
