# Generated by Django 5.2.9 on 2026-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_post_replay_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='platform',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
