# Generated by Django 5.2.9 on 2026-05-11 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_communitymembership'),
        ('post', '0017_share_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_pinned',
            new_name='community_pinned',
        ),
        migrations.AddField(
            model_name='post',
            name='community_pin_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pin_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_pin_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='post.post'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'profile_pinned', 'profile_pin_order'], name='post_post_user_id_03467a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', 'community_pinned', 'community_pin_order'], name='post_post_communi_146093_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'created_at'], name='post_post_user_id_b2741b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', 'created_at'], name='post_post_communi_2372c8_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['profile_pinned'], name='post_post_profile_0a4a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community_pinned'], name='post_post_communi_60585f_idx'),
        ),
    ]
