# Generated by Django 5.2.9 on 2026-05-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_rename_is_pinned_post_community_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
