# Generated by Django 5.2.9 on 2026-05-16 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_post_is_rejected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repost',
            name='quote_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repost',
            name='repost_type',
            field=models.CharField(choices=[('normal', 'Normal Repost'), ('quote', 'Quote Repost')], default='normal', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='repost',
            unique_together={('user', 'post', 'repost_type')},
        ),
    ]
