# Generated by Django 5.2.9 on 2026-05-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_communityinvite'),
        ('post', '0021_post_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='communities.community'),
        ),
    ]
