# Generated by Django 5.2.9 on 2026-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_repost_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
