# Generated by Django 5.2.9 on 2026-07-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_alter_post_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
