# Generated by Django 5.2.9 on 2026-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_post_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='client_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
