# Generated by Django 5.2.9 on 2026-08-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_comment_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client_post_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
