# Generated by Django 5.2.9 on 2026-08-08 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('post', '0026_post_client_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_media', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
