# Generated by Django 5.2.9 on 2026-08-14 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_community_cover_image_asset_and_more'),
        ('post', '0027_postmedia_asset_postmedia_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='share',
            name='platform',
        ),
        migrations.AddField(
            model_name='share',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='communities.community'),
        ),
        migrations.AddField(
            model_name='share',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='share',
            name='share_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('user', 'post', 'community'), name='unique_user_post_community_share'),
        ),
    ]
