# Generated by Django 5.2.9 on 2026-08-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_alter_share_options_remove_share_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='platform',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
