# Generated by Django 5.2.9 on 2026-08-14 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_community_cover_image_asset_and_more'),
        ('post', '0029_share_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='share',
            name='unique_user_post_community_share',
        ),
        migrations.AddField(
            model_name='share',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(condition=models.Q(('community__isnull', False), ('is_deleted', False)), fields=('user', 'post', 'community'), name='unique_active_community_share'),
        ),
    ]
