# Generated by Django 5.2.9 on 2026-08-15 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_remove_share_unique_user_post_community_share_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'created_at'], name='post_bookma_post_id_663bce_idx'), models.Index(fields=['user', 'created_at'], name='post_bookma_user_id_1d0ce3_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_bookmark')],
            },
        ),
    ]
