# Generated by Django 5.2.9 on 2026-08-16 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_user_post_bookmark',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='post.repost'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='post.share'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['repost', 'created_at'], name='post_bookma_repost__ca83b7_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['share', 'created_at'], name='post_bookma_share_i_f423bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('repost__isnull', True), ('share__isnull', True)), fields=('user', 'post'), name='unique_user_post_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('repost__isnull', False)), fields=('user', 'repost'), name='unique_user_repost_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('share__isnull', False)), fields=('user', 'share'), name='unique_user_share_bookmark'),
        ),
    ]
