# wallet/constants.py

from decimal import Decimal

DEFAULT_CURRENCY = "NGN"

SUPPORTED_CURRENCIES = (
    "NGN",
    "USD",
    "GBP",
    "EUR",
)

ZERO = Decimal("0.00")

MIN_TRANSACTION_AMOUNT = Decimal("0.01")

# Minimum amount a creator can withdraw.
MIN_WITHDRAWAL_AMOUNT = Decimal("1000.00")

# Maximum amount allowed in a single withdrawal.
MAX_WITHDRAWAL_AMOUNT = Decimal("5000000.00")

WALLET_DECIMAL_PLACES = 2

WALLET_MAX_DIGITS = 18

TRANSACTION_EARNING = "earning"
TRANSACTION_REWARD = "reward"
TRANSACTION_WITHDRAWAL = "withdrawal"
TRANSACTION_REFUND = "refund"
TRANSACTION_ADJUSTMENT = "adjustment"


TRANSACTION_TYPES = (
    TRANSACTION_EARNING,
    TRANSACTION_REWARD,
    TRANSACTION_WITHDRAWAL,
    TRANSACTION_REFUND,
    TRANSACTION_ADJUSTMENT,
)

TRANSACTION_CREDIT = "credit"
TRANSACTION_DEBIT = "debit"


TRANSACTION_DIRECTIONS = (
    TRANSACTION_CREDIT,
    TRANSACTION_DEBIT,
)

TRANSACTION_PENDING = "pending"
TRANSACTION_COMPLETED = "completed"
TRANSACTION_FAILED = "failed"
TRANSACTION_CANCELLED = "cancelled"
TRANSACTION_REVERSED = "reversed"


TRANSACTION_STATUSES = (
    TRANSACTION_PENDING,
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    TRANSACTION_CANCELLED,
    TRANSACTION_REVERSED,
)

REVENUE_ADS = "ads"
REVENUE_SUBSCRIPTIONS = "subscriptions"
REVENUE_TIPS = "tips"
REVENUE_REWARDS = "rewards"
REVENUE_SPONSORSHIP = "sponsorship"
REVENUE_CONTENT = "content"
REVENUE_OTHER = "other"


REVENUE_SOURCES = (
    REVENUE_ADS,
    REVENUE_SUBSCRIPTIONS,
    REVENUE_TIPS,
    REVENUE_REWARDS,
    REVENUE_SPONSORSHIP,
    REVENUE_CONTENT,
    REVENUE_OTHER,
)

REVENUE_PENDING = "pending"
REVENUE_CONFIRMED = "confirmed"
REVENUE_CANCELLED = "cancelled"
REVENUE_REVERSED = "reversed"


REVENUE_STATUSES = (
    REVENUE_PENDING,
    REVENUE_CONFIRMED,
    REVENUE_CANCELLED,
    REVENUE_REVERSED,
)

WITHDRAWAL_PENDING = "pending"
WITHDRAWAL_PROCESSING = "processing"
WITHDRAWAL_COMPLETED = "completed"
WITHDRAWAL_FAILED = "failed"
WITHDRAWAL_CANCELLED = "cancelled"


WITHDRAWAL_STATUSES = (
    WITHDRAWAL_PENDING,
    WITHDRAWAL_PROCESSING,
    WITHDRAWAL_COMPLETED,
    WITHDRAWAL_FAILED,
    WITHDRAWAL_CANCELLED,
)

PAYOUT_PENDING = "pending"
PAYOUT_PROCESSING = "processing"
PAYOUT_COMPLETED = "completed"
PAYOUT_FAILED = "failed"
PAYOUT_REVERSED = "reversed"


PAYOUT_STATUSES = (
    PAYOUT_PENDING,
    PAYOUT_PROCESSING,
    PAYOUT_COMPLETED,
    PAYOUT_FAILED,
    PAYOUT_REVERSED,
)

REWARD_PENDING = "pending"
REWARD_AVAILABLE = "available"
REWARD_CLAIMED = "claimed"
REWARD_EXPIRED = "expired"
REWARD_CANCELLED = "cancelled"


REWARD_STATUSES = (
    REWARD_PENDING,
    REWARD_AVAILABLE,
    REWARD_CLAIMED,
    REWARD_EXPIRED,
    REWARD_CANCELLED,
)

PERIOD_7D = "7d"
PERIOD_30D = "30d"
PERIOD_90D = "90d"
PERIOD_1Y = "1y"


MONETIZATION_PERIODS = (
    PERIOD_7D,
    PERIOD_30D,
    PERIOD_90D,
    PERIOD_1Y,
)

PERIOD_DAYS = {
    PERIOD_7D: 7,
    PERIOD_30D: 30,
    PERIOD_90D: 90,
    PERIOD_1Y: 365,
}

DEFAULT_PERIOD = PERIOD_30D

DEFAULT_PAGE_SIZE = 20

MAX_PAGE_SIZE = 100

WALLET_REFERENCE_PREFIX = "WAL"

TRANSACTION_REFERENCE_PREFIX = "TXN"

REVENUE_REFERENCE_PREFIX = "REV"

WITHDRAWAL_REFERENCE_PREFIX = "WDR"

PAYOUT_REFERENCE_PREFIX = "PAY"

REWARD_REFERENCE_PREFIX = "RWD"

PAYOUT_PROVIDER_PAYSTACK = "paystack"
PAYOUT_PROVIDER_FLUTTERWAVE = "flutterwave"
PAYOUT_PROVIDER_MANUAL = "manual"


SUPPORTED_PAYOUT_PROVIDERS = (
    PAYOUT_PROVIDER_PAYSTACK,
    PAYOUT_PROVIDER_FLUTTERWAVE,
    PAYOUT_PROVIDER_MANUAL,
)

REQUIRE_VERIFIED_BANK_ACCOUNT = True

REQUIRE_ACCOUNT_OWNER_MATCH = True

DEFAULT_CREATOR_REVENUE_SHARE = Decimal("0.70")


# Platform share.

DEFAULT_PLATFORM_REVENUE_SHARE = Decimal("0.30")

DEFAULT_GOAL_CURRENCY = DEFAULT_CURRENCY

MAX_ACTIVE_GOALS_PER_USER = 5

DATE_FILTER_ALL = "all"
DATE_FILTER_7D = "7d"
DATE_FILTER_30D = "30d"
DATE_FILTER_90D = "90d"
DATE_FILTER_1Y = "1y"

DATE_FILTERS = (
    DATE_FILTER_ALL,
    DATE_FILTER_7D,
    DATE_FILTER_30D,
    DATE_FILTER_90D,
    DATE_FILTER_1Y,
)

DASHBOARD_TRANSACTION_LIMIT = 10

DASHBOARD_PAYOUT_LIMIT = 10

DASHBOARD_TOP_CONTENT_LIMIT = 5

DASHBOARD_REVENUE_SOURCE_LIMIT = 10

DASHBOARD_INSIGHT_LIMIT = 6

REFERENCE_MAX_LENGTH = 100

PROVIDER_REFERENCE_MAX_LENGTH = 150


ERROR_INSUFFICIENT_BALANCE = "insufficient_balance"

ERROR_INVALID_AMOUNT = "invalid_amount"

ERROR_MINIMUM_WITHDRAWAL = "minimum_withdrawal"

ERROR_MAXIMUM_WITHDRAWAL = "maximum_withdrawal"

ERROR_BANK_ACCOUNT_NOT_FOUND = "bank_account_not_found"

ERROR_BANK_ACCOUNT_NOT_VERIFIED = "bank_account_not_verified"

ERROR_BANK_ACCOUNT_INACTIVE = "bank_account_inactive"

ERROR_WALLET_NOT_FOUND = "wallet_not_found"

ERROR_WITHDRAWAL_NOT_FOUND = "withdrawal_not_found"

ERROR_TRANSACTION_NOT_FOUND = "transaction_not_found"

ERROR_ALREADY_PROCESSED = "already_processed"

ERROR_INVALID_STATUS = "invalid_status"


CURRENCY_DECIMAL_PLACES = {
    "NGN": 2,
    "USD": 2,
    "GBP": 2,
    "EUR": 2,
}


CURRENCY_SYMBOLS = {
    "NGN": "₦",
    "USD": "$",
    "GBP": "£",
    "EUR": "€",
}