# wallets/models.py

from decimal import Decimal

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Q

ZERO = Decimal("0.00")

class TimeStampedModel(models.Model):
    """
    Base model for created/updated timestamps.
    """

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Wallet(TimeStampedModel):
    """
    One financial wallet per Tribe user.

    available_balance:
        Money currently available for withdrawal.

    pending_balance:
        Money earned but not yet available.

    lifetime_earnings:
        Total earnings generated by the creator.

    lifetime_withdrawn:
        Total successfully withdrawn by the creator.
    """

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="wallet",
    )

    currency = models.CharField(
        max_length=3,
        default="NGN",
    )

    available_balance = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        default=ZERO,
        validators=[MinValueValidator(ZERO)],
    )

    pending_balance = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        default=ZERO,
        validators=[MinValueValidator(ZERO)],
    )

    lifetime_earnings = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        default=ZERO,
        validators=[MinValueValidator(ZERO)],
    )

    lifetime_withdrawn = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        default=ZERO,
        validators=[MinValueValidator(ZERO)],
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.user} Wallet"

    @property
    def total_balance(self):
        return (
            self.available_balance +
            self.pending_balance
        )

class BankAccount(TimeStampedModel):
    """
    Creator payout account.

    The actual withdrawal flow should verify the account
    before allowing money to be sent.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="bank_accounts",
    )

    bank_name = models.CharField(
        max_length=150,
    )

    account_name = models.CharField(
        max_length=150,
    )

    account_number = models.CharField(
        max_length=30,
    )

    bank_code = models.CharField(
        max_length=20,
    )

    is_verified = models.BooleanField(
        default=False,
    )

    is_default = models.BooleanField(
        default=False,
    )

    is_active = models.BooleanField(
        default=True,
    )

    # Useful when using Paystack/Flutterwave/etc.
    provider_recipient_code = models.CharField(
        max_length=150,
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ["-is_default", "-created_at"]

        constraints = [
            models.UniqueConstraint(
                fields=[
                    "user",
                    "bank_code",
                    "account_number",
                ],
                name="unique_user_bank_account",
            ),

            models.UniqueConstraint(
                fields=["user"],
                condition=Q(is_default=True),
                name="one_default_bank_account_per_user",
            ),
        ]

        indexes = [
            models.Index(
                fields=["user", "is_active"],
            ),
        ]

    def __str__(self):
        return (
            f"{self.bank_name} - "
            f"{self.account_name}"
        )

class Revenue(TimeStampedModel):
    """
    Represents money generated by a creator.

    Revenue is the source event.
    WalletTransaction is the financial ledger entry.
    """

    SOURCE_CHOICES = [
        ("ads", "Ads"),
        ("subscriptions", "Subscriptions"),
        ("tips", "Tips"),
        ("rewards", "Rewards"),
        ("sponsorship", "Sponsorship"),
        ("content", "Content"),
        ("other", "Other"),
    ]

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("confirmed", "Confirmed"),
        ("cancelled", "Cancelled"),
        ("reversed", "Reversed"),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="revenues",
    )

    source = models.CharField(
        max_length=30,
        choices=SOURCE_CHOICES,
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="pending",
    )

    amount = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        validators=[MinValueValidator(ZERO)],
    )

    currency = models.CharField(
        max_length=3,
        default="NGN",
    )

    # Generic content reference.
    # This allows posts, reels, communities, etc.
    content_type = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )

    content_id = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )

    # External source reference.
    provider_reference = models.CharField(
        max_length=150,
        blank=True,
        null=True,
    )

    metadata = models.JSONField(
        default=dict,
        blank=True,
    )

    confirmed_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ["-created_at"]

        indexes = [
            models.Index(
                fields=["user", "-created_at"],
            ),
            models.Index(
                fields=["user", "source"],
            ),
            models.Index(
                fields=["user", "status"],
            ),
            models.Index(
                fields=[
                    "content_type",
                    "content_id",
                ],
            ),
        ]

    def __str__(self):
        return (
            f"{self.user} - "
            f"{self.source} - "
            f"{self.amount} {self.currency}"
        )

class WalletTransaction(TimeStampedModel):
    """
    Immutable financial ledger entry.

    Every movement of money through the wallet should have
    a corresponding transaction.
    """

    TYPE_CHOICES = [
        ("earning", "Earning"),
        ("reward", "Reward"),
        ("withdrawal", "Withdrawal"),
        ("refund", "Refund"),
        ("adjustment", "Adjustment"),
    ]

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("cancelled", "Cancelled"),
        ("reversed", "Reversed"),
    ]

    DIRECTION_CHOICES = [
        ("credit", "Credit"),
        ("debit", "Debit"),
    ]

    wallet = models.ForeignKey(
        Wallet,
        on_delete=models.PROTECT,
        related_name="transactions",
    )

    reward = models.ForeignKey(
        "AudienceReward",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="wallet_transactions",
    )

    transaction_type = models.CharField(
        max_length=30,
        choices=TYPE_CHOICES,
    )

    direction = models.CharField(
        max_length=10,
        choices=DIRECTION_CHOICES,
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="pending",
    )

    amount = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        validators=[
            MinValueValidator(
                Decimal("0.01")
            )
        ],
    )

    currency = models.CharField(
        max_length=3,
        default="NGN",
    )

    description = models.CharField(
        max_length=255,
    )

    reference = models.CharField(
        max_length=100,
        unique=True,
        db_index=True,
    )

    # Optional link to the source revenue.
    revenue = models.ForeignKey(
        Revenue,
        on_delete=models.PROTECT,
        related_name="transactions",
        blank=True,
        null=True,
    )

    # Optional link to withdrawal.
    withdrawal = models.ForeignKey(
        "Withdrawal",
        on_delete=models.PROTECT,
        related_name="transactions",
        blank=True,
        null=True,
    )

    metadata = models.JSONField(
        default=dict,
        blank=True,
    )

    completed_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ["-created_at"]

        indexes = [
            models.Index(
                fields=[
                    "wallet",
                    "-created_at",
                ],
            ),
            models.Index(
                fields=[
                    "wallet",
                    "status",
                ],
            ),
            models.Index(
                fields=[
                    "wallet",
                    "transaction_type",
                ],
            ),
            models.Index(
                fields=[
                    "transaction_type",
                    "status",
                ]
            ),
            models.Index(
                fields=[
                    "reference",
                ]
            ),
        ]

    def __str__(self):
        return (
            f"{self.reference} - "
            f"{self.amount} {self.currency}"
        )

class Withdrawal(TimeStampedModel):
    """
    Creator withdrawal request.
    """

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("processing", "Processing"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("cancelled", "Cancelled"),
    ]

    wallet = models.ForeignKey(
        Wallet,
        on_delete=models.PROTECT,
        related_name="withdrawals",
    )

    bank_account = models.ForeignKey(
        BankAccount,
        on_delete=models.PROTECT,
        related_name="withdrawals",
    )

    amount = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        validators=[
            MinValueValidator(
                Decimal("0.01")
            )
        ],
    )

    currency = models.CharField(
        max_length=3,
        default="NGN",
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="pending",
    )

    reference = models.CharField(
        max_length=100,
        unique=True,
        db_index=True,
    )

    provider_reference = models.CharField(
        max_length=150,
        blank=True,
        null=True,
    )

    failure_reason = models.TextField(
        blank=True,
    )

    requested_at = models.DateTimeField(
        auto_now_add=True,
    )

    processed_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    completed_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ["-created_at"]

        indexes = [
            models.Index(
                fields=[
                    "wallet",
                    "-created_at",
                ],
            ),
            models.Index(
                fields=[
                    "wallet",
                    "status",
                ],
            ),
        ]

    def __str__(self):
        return (
            f"{self.reference} - "
            f"{self.amount} {self.currency}"
        )

class Payout(TimeStampedModel):
    """
    Represents the actual payout processing result.
    """

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("processing", "Processing"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("reversed", "Reversed"),
    ]

    wallet = models.ForeignKey(
        Wallet,
        on_delete=models.PROTECT,
        related_name="payouts",
    )

    withdrawal = models.OneToOneField(
        Withdrawal,
        on_delete=models.PROTECT,
        related_name="payout",
    )

    amount = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        validators=[
            MinValueValidator(
                Decimal("0.01")
            )
        ],
    )

    currency = models.CharField(
        max_length=3,
        default="NGN",
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="pending",
    )

    provider = models.CharField(
        max_length=50,
        blank=True,
    )

    provider_reference = models.CharField(
        max_length=150,
        blank=True,
        null=True,
    )

    provider_response = models.JSONField(
        default=dict,
        blank=True,
    )

    failure_reason = models.TextField(
        blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    processed_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    completed_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ["-created_at"]

        indexes = [
            models.Index(
                fields=[
                    "wallet",
                    "-created_at",
                ],
            ),
            models.Index(
                fields=[
                    "wallet",
                    "status",
                ],
            ),
        ]

    def __str__(self):
        return (
            f"Payout {self.id} - "
            f"{self.amount} {self.currency}"
        )

class AudienceReward(TimeStampedModel):
    """
    Money/rewards generated for or by audience engagement.
    """

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("available", "Available"),
        ("claimed", "Claimed"),
        ("expired", "Expired"),
        ("cancelled", "Cancelled"),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="audience_rewards",
    )

    name = models.CharField(
        max_length=150,
    )

    description = models.TextField(
        blank=True,
    )

    amount = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        default=ZERO,
        validators=[MinValueValidator(ZERO)],
    )

    currency = models.CharField(
        max_length=3,
        default="NGN",
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="pending",
    )

    reference = models.CharField(
        max_length=100,
        unique=True,
    )

    metadata = models.JSONField(
        default=dict,
        blank=True,
    )

    available_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    claimed_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    expires_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ["-created_at"]

        indexes = [
            models.Index(
                fields=[
                    "user",
                    "-created_at",
                ],
            ),
            models.Index(
                fields=[
                    "user",
                    "status",
                ],
            ),
        ]

    def __str__(self):
        return (
            f"{self.name} - "
            f"{self.user}"
        )

class MonetizationGoal(TimeStampedModel):
    """
    Creator earnings goal.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="monetization_goals",
    )

    title = models.CharField(
        max_length=150,
    )

    target_amount = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        validators=[
            MinValueValidator(
                Decimal("0.01")
            )
        ],
    )

    current_amount = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        default=ZERO,
        validators=[MinValueValidator(ZERO)],
    )

    currency = models.CharField(
        max_length=3,
        default="NGN",
    )

    is_active = models.BooleanField(
        default=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    completed_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ["-created_at"]

        indexes = [
            models.Index(
                fields=[
                    "user",
                    "is_active",
                ],
            ),
        ]

    def __str__(self):
        return (
            f"{self.user} - "
            f"{self.title}"
        )

    @property
    def progress_percentage(self):
        if self.target_amount <= ZERO:
            return Decimal("0")

        percentage = (
            self.current_amount /
            self.target_amount
        ) * Decimal("100")

        return min(
            percentage,
            Decimal("100"),
        )