# Generated by Django 5.2.9 on 2026-04-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_key',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
