# Generated by Django 5.2.9 on 2026-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_remove_chat_is_group_remove_message_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CommunityChatJoinRequest',
        ),
    ]
