# Generated by Django 5.2.9 on 2026-05-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_messageencryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
