# Generated by Django 5.2.9 on 2026-06-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_message_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_source',
            field=models.CharField(blank=True, choices=[('upload', 'Upload'), ('external', 'External')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('gif', 'GIF'), ('sticker', 'Sticker')], default='text', max_length=10, null=True),
        ),
    ]
