# Generated by Django 5.2.9 on 2026-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_message_media_source_alter_message_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
