# Generated by Django 5.2.9 on 2026-06-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_alter_message_media_source_chatparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='last_delivered_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chats.message'),
        ),
    ]
