# Generated by Django 5.2.9 on 2026-06-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0018_messageblockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='duration',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_url',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='message',
            name='thumbnail',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
