# Generated by Django 5.2.9 on 2026-07-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_message_duration_alter_message_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='waveform',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('gallery', 'Gallery'), ('gif', 'GIF'), ('sticker', 'Sticker')], default='text', max_length=10, null=True),
        ),
    ]
