# Generated by Django 5.2.9 on 2026-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0020_message_waveform_alter_message_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
