# Generated by Django 5.2.9 on 2026-07-17 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0021_message_client_id'),
        ('communities', '0012_triberequest_tribe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('ringing', 'Ringing'), ('joined', 'Joined'), ('declined', 'Declined'), ('missed', 'Missed'), ('left', 'Left')], default='invited', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('mic_on', models.BooleanField(default=True)),
                ('camera_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_text', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_typing', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceRoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('mic_on', models.BooleanField(default=True)),
                ('speaker', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='communityanalytics',
            name='community',
        ),
        migrations.RemoveField(
            model_name='messageencryption',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messageencryption',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='messagereport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagereport',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagereport',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='messagereport',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='community',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='threadreply',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='threadreply',
            name='sender',
        ),
        migrations.RenameField(
            model_name='chatparticipant',
            old_name='created_at',
            new_name='joined_at',
        ),
        migrations.RenameField(
            model_name='communitychatsettings',
            old_name='can_send_media',
            new_name='allow_media',
        ),
        migrations.RemoveField(
            model_name='call',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='allow_media',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='allow_voice_notes',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='communitychatsettings',
            name='can_send_links',
        ),
        migrations.RemoveField(
            model_name='communitychatsettings',
            name='can_send_messages',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ephemeral',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seen_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.RemoveField(
            model_name='voiceroom',
            name='participants',
        ),
        migrations.AddField(
            model_name='call',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chats.chat'),
        ),
        migrations.AddField(
            model_name='call',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='started_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('owner', 'Owner')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitychatsettings',
            name='allow_voice_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
        ),
        migrations.AddField(
            model_name='notification',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to='communities.community'),
        ),
        migrations.AddField(
            model_name='notification',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('reaction', 'Reaction'), ('mention', 'Mention'), ('reply', 'Reply'), ('call', 'Call'), ('missed_call', 'Missed Call'), ('community', 'Community'), ('announcement', 'Announcement'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=15),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('ongoing', 'Ongoing'), ('ended', 'Ended'), ('missed', 'Missed')], default='ringing', max_length=15),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('community', 'Community'), ('channel', 'Channel')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='voiceroom',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_rooms', to='communities.community'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_id'], name='chats_messa_client__712de0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='chats_messa_created_8b0743_idx'),
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chats.call'),
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageedit',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageedit',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='chats.message'),
        ),
        migrations.AddField(
            model_name='messageread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.message'),
        ),
        migrations.AddField(
            model_name='messageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typingstatus',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
        ),
        migrations.AddField(
            model_name='typingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voiceroomparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chats.voiceroom'),
        ),
        migrations.AddField(
            model_name='voiceroomparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_room_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommunityAnalytics',
        ),
        migrations.DeleteModel(
            name='MessageEncryption',
        ),
        migrations.DeleteModel(
            name='MessageReport',
        ),
        migrations.DeleteModel(
            name='MessageThread',
        ),
        migrations.DeleteModel(
            name='ThreadReply',
        ),
        migrations.AlterUniqueTogether(
            name='callparticipant',
            unique_together={('call', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='voiceroomparticipant',
            unique_together={('room', 'user')},
        ),
    ]
