# Generated by Django 5.2.9 on 2026-07-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0022_callparticipant_messageedit_messageread_typingstatus_and_more'),
        ('communities', '0013_remove_communitymembership_banned_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityban',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='communityban',
            name='banned_by',
        ),
        migrations.RemoveField(
            model_name='communityban',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityban',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='communitymute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='communitymute',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitymute',
            name='muted_by',
        ),
        migrations.RemoveField(
            model_name='communitymute',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communities.community'),
        ),
        migrations.DeleteModel(
            name='CommunityAuditLog',
        ),
        migrations.DeleteModel(
            name='CommunityBan',
        ),
        migrations.DeleteModel(
            name='CommunityMute',
        ),
    ]
