# Generated by Django 5.2.9 on 2026-08-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0023_alter_communityban_unique_together_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='message',
            name='media_assets',
            field=models.ManyToManyField(blank=True, related_name='messages', to='media.mediaasset'),
        ),
    ]
