# Generated by Django 5.2.9 on 2026-08-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0025_remove_message_mentions_message_mention_all_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_private_chat',
        ),
    ]
