# Generated by Django 5.2.9 on 2026-08-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0026_remove_chat_unique_private_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_media_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
