# Generated by Django 5.2.9 on 2026-08-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0027_message_external_media_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_source',
            field=models.CharField(blank=True, choices=[('upload', 'Upload'), ('external', 'External'), ('forward', 'Forward')], default=None, max_length=20, null=True),
        ),
    ]
