# Generated by Django 5.2.9 on 2026-08-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='multipart_part_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='multipart_upload_id',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='thumbnail_status',
            field=models.CharField(choices=[('none', 'None'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=20),
        ),
    ]
