# Generated by Django 5.2.9 on 2026-08-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediaasset_multipart_part_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='media_id',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('gif', 'GIF'), ('sticker', 'Sticker')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='multipart_upload_id',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='object_key',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='thumbnail_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='thumbnail_status',
            field=models.CharField(choices=[('none', 'None'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=100),
        ),
    ]
