# Generated by Django 5.2.9 on 2026-08-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_mediaasset_media_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
