# Generated by Django 5.2.9 on 2026-03-14 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified_user_followers_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers_count',
            new_name='stars_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'starred_user')},
            },
        ),
    ]
