# Generated by Django 5.2.9 on 2026-03-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_city_user_country_user_cover_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='user',
            new_name='star',
        ),
        migrations.AddField(
            model_name='user',
            name='starred_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='star',
            unique_together={('star', 'starred_user')},
        ),
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['star'], name='users_star_star_id_6d6830_idx'),
        ),
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['starred_user'], name='users_star_starred_fcb301_idx'),
        ),
    ]
