# Generated by Django 5.2.9 on 2026-03-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_star_star_user_starred_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
    ]
