# Generated by Django 5.2.9 on 2026-03-26 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_onboarding_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='stars',
            field=models.ManyToManyField(related_name='starred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
