# Generated by Django 5.2.9 on 2026-04-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_last_login_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
