# Generated by Django 5.2.9 on 2026-04-26 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userkeypair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkeypair',
            name='private_key',
        ),
        migrations.AddField(
            model_name='userkeypair',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
