# Generated by Django 5.2.9 on 2026-04-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_savedlogindevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlogindevice',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedlogindevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savedlogindevice',
            name='refresh_token_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedlogindevice',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
