# Generated by Django 5.2.9 on 2026-05-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_savedlogindevice_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedlogindevice',
            unique_together=set(),
        ),
    ]
