# Generated by Django 5.2.9 on 2026-06-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_is_deactivated_blockeduser_muteduser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
    ]
