# Generated by Django 5.2.9 on 2026-07-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creator_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.AddField(
            model_name='user',
            name='what_do_you_do',
            field=models.CharField(blank=True, help_text='Tell people what you do', max_length=100),
        ),
    ]
