# Generated by Django 5.2.9 on 2026-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
