# Generated by Django 5.2.9 on 2026-08-08 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('users', '0027_alter_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_users', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_users', to='media.mediaasset'),
        ),
    ]
