# Generated by Django 5.2.9 on 2026-08-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_avatar_asset_user_cover_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockeduser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='muteduser',
            options={'ordering': ['-created_at']},
        ),
    ]
