# Generated by Django 5.2.9 on 2026-08-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_profileview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
