# wallet/services/revenue.py

from django.db import transaction

from wallets.models import Revenue

from wallets.services.earnings import (
    add_earning,
)

from wallets.utils.currency import (
    validate_positive_amount,
)

from wallets.utils.reference import (
    generate_revenue_reference,
)


def record_revenue(
    user,
    source: str,
    amount,
    *,
    currency: str = "NGN",
    content_type: str | None = None,
    content_id: str | None = None,
    metadata: dict | None = None,
    pending: bool = True,
    description: str | None = None,
):
    """
    Record revenue generated by a creator.

    This creates the Revenue record and then sends the
    corresponding amount into the creator's wallet.

    The whole operation is atomic.

    If wallet processing fails, the Revenue record is
    rolled back as well.
    """

    amount = validate_positive_amount(
        amount
    )

    currency = currency.upper()

    if metadata is None:
        metadata = {}

    with transaction.atomic():

        revenue = Revenue.objects.create(
            user=user,
            source=source,
            amount=amount,
            currency=currency,
            content_type=content_type,
            content_id=content_id,
            metadata={
                **metadata,
                "revenue_reference":
                    generate_revenue_reference(),
            },
        )

        # Import here to avoid circular dependency.
        from wallet.services.wallet import (
            get_or_create_wallet,
        )

        wallet = get_or_create_wallet(
            user=user,
            currency=currency,
        )

        wallet, wallet_transaction = add_earning(
            wallet=wallet,
            amount=amount,
            description=(
                description
                or f"{source.title()} revenue"
            ),
            pending=pending,
            currency=currency,
            metadata={
                "revenue_id": revenue.id,
                "source": source,
                "content_type": content_type,
                "content_id": content_id,
            },
        )

        return {
            "revenue": revenue,
            "wallet": wallet,
            "transaction": wallet_transaction,
        }


def record_ad_revenue(
    user,
    amount,
    *,
    content_type: str | None = None,
    content_id: str | None = None,
    metadata: dict | None = None,
    pending: bool = True,
):
    """
    Convenience method for advertising revenue.
    """

    return record_revenue(
        user=user,
        source="ads",
        amount=amount,
        currency="NGN",
        content_type=content_type,
        content_id=content_id,
        metadata=metadata,
        pending=pending,
        description="Advertising revenue",
    )


def record_tip_revenue(
    user,
    amount,
    *,
    content_type: str | None = None,
    content_id: str | None = None,
    metadata: dict | None = None,
):
    """
    Convenience method for tips.
    """

    return record_revenue(
        user=user,
        source="tips",
        amount=amount,
        currency="NGN",
        content_type=content_type,
        content_id=content_id,
        metadata=metadata,
        pending=False,
        description="Creator tip",
    )


def record_subscription_revenue(
    user,
    amount,
    *,
    content_type: str | None = None,
    content_id: str | None = None,
    metadata: dict | None = None,
):
    """
    Convenience method for subscription revenue.
    """

    return record_revenue(
        user=user,
        source="subscriptions",
        amount=amount,
        currency="NGN",
        content_type=content_type,
        content_id=content_id,
        metadata=metadata,
        pending=True,
        description="Subscription revenue",
    )


def record_sponsorship_revenue(
    user,
    amount,
    *,
    content_type: str | None = None,
    content_id: str | None = None,
    metadata: dict | None = None,
):
    """
    Convenience method for sponsorship revenue.
    """

    return record_revenue(
        user=user,
        source="sponsorship",
        amount=amount,
        currency="NGN",
        content_type=content_type,
        content_id=content_id,
        metadata=metadata,
        pending=True,
        description="Sponsorship revenue",
    )