# Generated by Django 5.2.9 on 2026-04-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='cover_image',
            field=models.ImageField(blank=True, default='community_covers/default.png', upload_to='communities'),
        ),
        migrations.AddField(
            model_name='community',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='communities'),
        ),
    ]
