# Generated by Django 5.2.9 on 2026-04-04 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_tribe_community_moderators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
