# Generated by Django 5.2.9 on 2026-04-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_tribe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='cover_image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/demo/image/upload/default.png'),
        ),
        migrations.AlterField(
            model_name='community',
            name='intro_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
