# Generated by Django 5.2.9 on 2026-07-02 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_triberequest_delete_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triberequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='triberequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='triberequest',
            name='request_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='triberequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triberequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tribe_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triberequest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribe_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triberequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
