# Generated by Django 5.2.9 on 2026-07-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_alter_triberequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triberequest',
            name='tribe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='communities.tribe'),
        ),
    ]
