# Generated by Django 5.2.9 on 2026-07-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_remove_communitymembership_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='allow_videos',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
