# Generated by Django 5.2.9 on 2026-07-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_community_allow_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='override_reels',
            field=models.BooleanField(default=False),
        ),
    ]
