# Generated by Django 5.2.9 on 2026-07-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0015_community_override_reels'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
