# Generated by Django 5.2.9 on 2026-08-08 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0017_alter_community_website'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='cover_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_cover_images', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='community',
            name='intro_video_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_intro_videos', to='media.mediaasset'),
        ),
    ]
