# Generated by Django 5.2.9 on 2026-08-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_community_cover_image_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.TextField(blank=True, default=''),
        ),
    ]
