# Generated by Django 5.2.9 on 2026-06-06 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_message_media_source_alter_message_media_type'),
        ('communities', '0010_triberequest_delete_report'),
        ('feedback', '0001_initial'),
        ('post', '0022_repost_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='target_tribe',
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('post', 'Post'), ('user', 'User'), ('message', 'Message'), ('community', 'Community')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='target_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to='communities.community'),
        ),
        migrations.AddField(
            model_name='report',
            name='target_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_reports', to='chats.message'),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to='post.post'),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'target_post'), name='unique_post_report'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'target_message'), name='unique_message_report'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'target_user'), name='unique_user_report'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'target_community'), name='unique_community_report'),
        ),
    ]
