# Generated by Django 5.2.9 on 2026-06-06 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_message_media_source_alter_message_media_type'),
        ('communities', '0010_triberequest_delete_report'),
        ('feedback', '0002_remove_report_target_tribe_report_report_type_and_more'),
        ('post', '0022_repost_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence'), ('nudity', 'Nudity'), ('misinformation', 'Misinformation'), ('copyright', 'Copyright'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'reason'], name='feedback_re_report__de7ced_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='feedback_re_status_edcc74_idx'),
        ),
    ]
