# Generated by Django 5.2.9 on 2026-06-10 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_report_details_alter_report_reason_and_more'),
        ('post', '0022_repost_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='target_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to='post.comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='target_repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repost_reports', to='post.repost'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('post', 'Post'), ('user', 'User'), ('message', 'Message'), ('community', 'Community'), ('comment', 'Comment')], max_length=20, null=True),
        ),
    ]
