# Generated by Django 5.2.9 on 2026-06-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_problemreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(blank=True, choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('not_satisfied', 'Not Satisfied')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
