# Generated by Django 5.2.9 on 2026-08-27 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0028_message_client_created_at_alter_message_media_source'),
        ('feedback', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='target_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports', to='chats.chat'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('post', 'Post'), ('user', 'User'), ('message', 'Message'), ('chat', 'Chat'), ('community', 'Community'), ('comment', 'Comment')], max_length=20, null=True),
        ),
    ]
